### ISSUE TITLE
Adicionar pause ao pressionar 'P'

### ISSUE THREAD

**Issue by victorinknov** [rodrigoKulb/alexKidd#17]

**Comment by rodrigoKulb** [comment]
@victorinknov veja se consegue acionar o pause também quando trocar de aba.

**Comment by victorinknov** [comment]
> @victorinknov veja se consegue acionar o pause também quando trocar de aba.

@rodrigoKulb feito!

**Comment by rodrigoKulb** [comment]
Colocar um opção para clicar na tela, para não travar no mobile, ou um botão boltar.

**Comment by victorinknov** [comment]
adicionar fallback pra previnir que a musica toque em background apos sair da aba

**Comment by rodrigoKulb** [comment]
@victorinknov ideia é utilizar o pause padrão do jogo com a tecla **C** vou finalizar a task pois já foi aplicado!
