### ISSUE TITLE
Autorização para aparecer no vídeo sobre o Alex Kidd

### ISSUE THREAD

**Issue by rodrigoKulb** [rodrigoKulb/alexKidd#24]
Olá @diegomagikal estou montando um vídeo sobre o repositório Alex Kidd, gostaria de saber se você autoriza falar sobre sua contribuição do repositório.

**Comment by diegomagikal** [comment]
@rodrigoKulb Opa, claro, fique à vontade! Não voltei a contribuir porque tenho estado bastante ocupado, mas assim que possível estarei por aqui novamente. P5.js é um objeto de estudo interessante, e seu repositório também, então nada melhor que unir as duas coisas!

**Comment by diegomagikal** [comment]
Iniciei um canal a uns meses atrás (https://www.youtube.com/c/doActionBR/) mas não tenho tido tempo para desenvolvê-lo. Talvez possamos fazer um crossover no futuro!

**Comment by rodrigoKulb** [comment]
@diegomagikal obrigado por responder, estou finalizando o vídeo acredito que vou postar ele depois do Natal.
Já estou inscrito no seu canal!!!! Bora pra cima!!
